
DROP TABLE IF EXISTS days;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sessions;

CREATE TABLE days (
  id SERIAL PRIMARY KEY,
  date DATE UNIQUE NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  hashedpw TEXT NOT NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,

  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,

  user_id INTEGER REFERENCES users (id),
  day_id INTEGER REFERENCES days (id)
);

CREATE TABLE sessions (
  id SERIAL PRIMARY KEY,
  token TEXT UNIQUE NOT NULL,
  refresh_token TEXT UNIQUE NOT NULL,
  expiration_date TIMESTAMP NOT NULL,

  user_id INTEGER REFERENCES users (id)
);
