
DROP TABLE IF EXISTS days;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE days (
  id INTEGER PRIMARY KEY,
  date TEXT UNIQUE NOT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  hashedpw TEXT NOT NULL
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  text TEXT NOT NULL,

  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,

  user_id INTEGER NOT NULL,
  day_id INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
  FOREIGN KEY(day_id) REFERENCES days(id)
);

CREATE TABLE sessions (
  id INTEGER PRIMARY KEY,
  token TEXT NOT NULL,
  expiration_date INTEGER NOT NULL,

  user_id INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
